services:
  frontend:
    labels:
      traefik.http.routers.wisdom-frontend-maint.rule: "Host(`${FRONTEND_DOMAIN}`) || Host(`www.${FRONTEND_DOMAIN}`)"
      traefik.http.routers.wisdom-frontend-maint.entrypoints: websecure
      traefik.http.routers.wisdom-frontend-maint.tls: "true"
      traefik.http.routers.wisdom-frontend-maint.tls.certresolver: letsencrypt
      traefik.http.routers.wisdom-frontend-maint.priority: "1000"
      traefik.http.routers.wisdom-frontend-maint.service: error-service@docker

  admin:
    labels:
      traefik.http.routers.wisdom-admin-maint.rule: "Host(`${ADMIN_DOMAIN}`)"
      traefik.http.routers.wisdom-admin-maint.entrypoints: websecure
      traefik.http.routers.wisdom-admin-maint.tls: "true"
      traefik.http.routers.wisdom-admin-maint.tls.certresolver: letsencrypt
      traefik.http.routers.wisdom-admin-maint.priority: "1000"
      traefik.http.routers.wisdom-admin-maint.service: error-service@docker

  api:
    labels:
      traefik.http.routers.wisdom-api-maint.rule: "Host(`${API_DOMAIN}`)"
      traefik.http.routers.wisdom-api-maint.entrypoints: websecure
      traefik.http.routers.wisdom-api-maint.tls: "true"
      traefik.http.routers.wisdom-api-maint.tls.certresolver: letsencrypt
      traefik.http.routers.wisdom-api-maint.priority: "1000"
      traefik.http.routers.wisdom-api-maint.service: error-service@docker